# Generated by Django 2.2.5 on 2019-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('B2B', 'Business-to-Business'), ('B2C', 'Business-to-Consumer'), ('B2A', 'Business-to-Anyone')], max_length=2)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('updated_at', models.DateField(verbose_name='date updated')),
            ],
        ),
    ]
